version: '3.3'
services:
  ckb:
    image: lumos/ckb-dev:v0.103.0
    build: ckb
    ports:
      - '8114:8114'
    networks:
      lumosnet:
        ipv4_address: 10.5.0.11
        aliases:
          - ckb
  ckb-indexer:
    image: nervos/ckb-indexer:0.3.2
    ports:
      - '8116:8116'
    environment:
      - RUST_LOG=info
    command: -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
    networks:
      lumosnet:
        ipv4_address: 10.5.0.12
        aliases:
          - ckb-indexer
networks:
  lumosnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
